
!ASSIGN DBNK LITERAL 'US';

OPEN <PRIMARY YES> #DBNK|.BNK; 

STRUCTURE SERIES ORIGIN 'ORIGIN SOURCE OF DATA' 200 A, UNITS 20 A, FTC 1 A, TYPE 1 A; 
ASSIGN CURRFREQ CURRENT FREQUENCY;

IF ('#CURRFREQ'=='MONTHLY');   ASSIGN MYFREQ LITERAL 'M'; END;
IF ('#CURRFREQ'=='QUARTERLY'); ASSIGN MYFREQ LITERAL 'Q'; END;
IF ('#CURRFREQ'=='ANNUAL');    ASSIGN MYFREQ LITERAL 'A'; END;

    IF ('#MYFREQ'=='M' OR '#MYFREQ'=='Q');
    ASSIGN  SEASNAME   LITERAL ' (SEAS.ADJ.)';
    ELSE
    ASSIGN  SEASNAME   LITERAL '';
    END;

!*****************************

ASSIGN AVAIL EXIST YXR@JP;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YXR@JP.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/EXJPUS/', UNITS='Yen/$', FTC = 'A', TYPE = 'L');
SERIES YXR@JP.|#MYFREQ|  'Japan / US Foreign Exchange Rate' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST CAPU@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CAPU@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/TCU/', UNITS='%', FTC = 'A', TYPE = '%');
SERIES CAPU@US.|#MYFREQ|  'CAPACITY UTILIZATION, U.S.|#SEASNAME|' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST CPI@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CPI@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cpi/home.htm', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES CPI@US.|#MYFREQ|  'CONSUMER PRICE INDEX, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST CPICORE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CPICORE@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cpi/home.htm', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES CPICORE@US.|#MYFREQ|  'CORE CONSUMER PRICE INDEX, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST CPICORENS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CPICORENS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cpi/home.htm', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES CPICORENS@US.|#MYFREQ|  'CORE CONSUMER PRICE INDEX, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST CPINS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CPINS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cpi/home.htm', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES CPINS@US.|#MYFREQ|  'CONSUMER PRICE INDEX, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAD@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAD@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAD@US.|#MYFREQ|  'ADMINISTRATIVE AND WASTE SVC JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EADNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EADNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EADNS@US.|#MYFREQ|  'ADMINISTRATIVE AND WASTE SVC JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAE@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAE@US.|#MYFREQ|  'ART AND ENTERTAINMENT JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAENS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAENS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAENS@US.|#MYFREQ|  'ART AND ENTERTAINMENT JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAF@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAF@US.|#MYFREQ|  'ACCOMMODATION AND FOOD SVC JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAFNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAFNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAFNS@US.|#MYFREQ|  'ACCOMMODATION AND FOOD SVC JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAFAC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAFAC@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAFAC@US.|#MYFREQ|  'ACCOMMODATION JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAFACNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAFACNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAFACNS@US.|#MYFREQ|  'ACCOMMODATION JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAFFD@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAFFD@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAFFD@US.|#MYFREQ|  'FOOD SERVICE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EAFFDNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EAFFDNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EAFFDNS@US.|#MYFREQ|  'FOOD SERVICE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ECT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ECT@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ECT@US.|#MYFREQ|  'CONSTRUCTION JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ECTNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ECTNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ECTNS@US.|#MYFREQ|  'CONSTRUCTION JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EED@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EED@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EED@US.|#MYFREQ|  'EDUCATION JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EEDNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EEDNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EEDNS@US.|#MYFREQ|  'EDUCATION JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EFI@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EFI@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EFI@US.|#MYFREQ|  'FINANCE AND INSURANCE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EFINS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EFINS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EFINS@US.|#MYFREQ|  'FINANCE AND INSURANCE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGV@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGV@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGV@US.|#MYFREQ|  'GOVERNMENT JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVNS@US.|#MYFREQ|  'GOVERNMENT JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVFD@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVFD@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVFD@US.|#MYFREQ|  'FEDERAL GOVERNMENT JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVFDNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVFDNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVFDNS@US.|#MYFREQ|  'FEDERAL GOVERNMENT JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVLC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVLC@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVLC@US.|#MYFREQ|  'LOCAL GOVERNMENT JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVLCNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVLCNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVLCNS@US.|#MYFREQ|  'LOCAL GOVERNMENT JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVST@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVST@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVST@US.|#MYFREQ|  'STATE GOVERNMENT JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EGVSTNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EGVSTNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EGVSTNS@US.|#MYFREQ|  'STATE GOVERNMENT JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EHC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EHC@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EHC@US.|#MYFREQ|  'HEALTH CARE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EHCNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EHCNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EHCNS@US.|#MYFREQ|  'HEALTH CARE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EIF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EIF@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EIF@US.|#MYFREQ|  'INFORMATION JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EIFNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EIFNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EIFNS@US.|#MYFREQ|  'INFORMATION JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMA@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMA@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMA@US.|#MYFREQ|  'MANAGEMENT JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMANS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMANS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMANS@US.|#MYFREQ|  'MANAGEMENT JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMI@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMI@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMI@US.|#MYFREQ|  'MINING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMINS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMINS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMINS@US.|#MYFREQ|  'MINING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMN@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMN@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMN@US.|#MYFREQ|  'MANUFACTURING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMNNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMNNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMNNS@US.|#MYFREQ|  'MANUFACTURING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMNDR@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMNDR@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMNDR@US.|#MYFREQ|  'DURABLE-GOODS MANUFACTURING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMNDRNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMNDRNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMNDRNS@US.|#MYFREQ|  'DURABLE-GOODS MANUFACTURING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMNND@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMNND@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMNND@US.|#MYFREQ|  'NONDURABLE-GOODS MANUFACTURING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMNNDNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMNNDNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMNNDNS@US.|#MYFREQ|  'NONDURABLE-GOODS MANUFACTURING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMPL@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMPL@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMPL@US.|#MYFREQ|  'EMPLOYMENT, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMPLNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMPLNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMPLNS@US.|#MYFREQ|  'EMPLOYMENT, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EOS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EOS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EOS@US.|#MYFREQ|  'OTHER SERVICES JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EOSNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EOSNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EOSNS@US.|#MYFREQ|  'OTHER SERVICES JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EPS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EPS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EPS@US.|#MYFREQ|  'PROF, SCI & TECH SVC JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EPSNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EPSNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EPSNS@US.|#MYFREQ|  'PROF, SCI & TECH SVC JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ERE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ERE@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ERE@US.|#MYFREQ|  'REAL ESTATE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ERENS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ERENS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ERENS@US.|#MYFREQ|  'REAL ESTATE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ERT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ERT@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ERT@US.|#MYFREQ|  'RETAIL TRADE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ERTNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ERTNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ERTNS@US.|#MYFREQ|  'RETAIL TRADE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ETW@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ETW@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ETW@US.|#MYFREQ|  'TRANSPORTATION AND WAREHOUSING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ETWNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ETWNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ETWNS@US.|#MYFREQ|  'TRANSPORTATION AND WAREHOUSING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EUT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EUT@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EUT@US.|#MYFREQ|  'UTILITIES JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EUTNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EUTNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EUTNS@US.|#MYFREQ|  'UTILITIES JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EWT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EWT@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EWT@US.|#MYFREQ|  'WHOLESALE TRADE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EWTNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EWTNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EWTNS@US.|#MYFREQ|  'WHOLESALE TRADE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_EDHC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_EDHC@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_EDHC@US.|#MYFREQ|  'EDUCATION AND HEALTH CARE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_EDHCNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_EDHCNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_EDHCNS@US.|#MYFREQ|  'EDUCATION AND HEALTH CARE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_FIR@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_FIR@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_FIR@US.|#MYFREQ|  'FINANCE AND REAL ESTATE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_FIRNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_FIRNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_FIRNS@US.|#MYFREQ|  'FINANCE AND REAL ESTATE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_GDSPR@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_GDSPR@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_GDSPR@US.|#MYFREQ|  'GOOD PRODUCING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_GDSPRNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_GDSPRNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_GDSPRNS@US.|#MYFREQ|  'GOOD PRODUCING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_LH@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_LH@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_LH@US.|#MYFREQ|  'LEISURE AND HOSPITALITY JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_LHNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_LHNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_LHNS@US.|#MYFREQ|  'LEISURE AND HOSPITALITY JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_NF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_NF@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_NF@US.|#MYFREQ|  'NONFARM JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_NFNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_NFNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_NFNS@US.|#MYFREQ|  'NONFARM JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_PBS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_PBS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_PBS@US.|#MYFREQ|  'PROFESSIONAL & BUS SVC JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_PBSNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_PBSNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_PBSNS@US.|#MYFREQ|  'PROFESSIONAL & BUS SVC JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_PR@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_PR@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_PR@US.|#MYFREQ|  'PRIVATE JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_PRNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_PRNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_PRNS@US.|#MYFREQ|  'PRIVATE JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_SVCPR@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_SVCPR@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_SVCPR@US.|#MYFREQ|  'SERVICE PROVIDING JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_SVCPRNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_SVCPRNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_SVCPRNS@US.|#MYFREQ|  'SERVICE PROVIDING JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_TTU@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_TTU@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_TTU@US.|#MYFREQ|  'TRADE, TRANSP & UTILITIES JOBS, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST E_TTUNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES E_TTUNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES E_TTUNS@US.|#MYFREQ|  'TRADE, TRANSP & UTILITIES JOBS, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST INF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES INF@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cpi/home.htm', UNITS='%', FTC = 'A', TYPE = '%');
SERIES INF@US.|#MYFREQ|  'INFLATION RATE, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST INFCORE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES INFCORE@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cpi/home.htm', UNITS='%', FTC = 'A', TYPE = '%');
SERIES INFCORE@US.|#MYFREQ|  'CORE INFLATION RATE, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST IP@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES IP@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/INDPRO', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES IP@US.|#MYFREQ|  'INDUSTRIAL PRODUCTION, U.S.|#SEASNAME|' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST LFP@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES LFP@US.|#MYFREQ| (ORIGIN='LF/N16', UNITS='%', FTC = 'A', TYPE = '%');
SERIES LFP@US.|#MYFREQ|  'LABOR FORCE PARTICIPATION RATE, U.S.|#SEASNAME|' SOURCE='BLS';
END;

ASSIGN AVAIL EXIST LFPNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES LFPNS@US.|#MYFREQ| (ORIGIN='LF/N16', UNITS='%', FTC = 'A', TYPE = '%');
SERIES LFPNS@US.|#MYFREQ|  'LABOR FORCE PARTICIPATION RATE, U.S.' SOURCE='BLS';
END;

ASSIGN AVAIL EXIST LF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES LF@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES LF@US.|#MYFREQ|  'CIVILIAN LABOR FORCE, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST LFNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES LFNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/ces/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES LFNS@US.|#MYFREQ|  'CIVILIAN LABOR FORCE, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST M2@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES M2@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/M2SL', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES M2@US.|#MYFREQ|  'M2 MONEY STOCK, U.S.|#SEASNAME|' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST M2NS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES M2NS@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/M2SL', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES M2NS@US.|#MYFREQ|  'M2 MONEY STOCK, U.S.' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST N@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES N@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/bea/dn/home/gdp.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES N@US.|#MYFREQ|  'TOTAL POPULATION, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST N15_UN@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES N15_UN@US.|#MYFREQ| (ORIGIN='http://esa.un.org/unpp/', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES N15_UN@US.|#MYFREQ|  '15+ POPULATION, U.S.|#SEASNAME|' SOURCE='UN';
END;


ASSIGN AVAIL EXIST RAAANS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES RAAANS@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/AAA/', UNITS='%', FTC = 'A', TYPE = '%');
SERIES RAAANS@US.|#MYFREQ|  'MOODYs SEASONED AAA CORPORATE BOND YIELD, U.S.' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST RFED@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES RFED@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/FEDFUNDS/', UNITS='%', FTC = 'A', TYPE = '%');
SERIES RFED@US.|#MYFREQ|  'FEDERAL FUNDS RATE, U.S.' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST RILGFCY10@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES RILGFCY10@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/GS10/115', UNITS='%', FTC = 'A', TYPE = '%');
SERIES RILGFCY10@US.|#MYFREQ|  '10-YEAR TREASURY CONSTANT MATURITY RATE, U.S.' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST RMORT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES RMORT@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/MORTG', UNITS='%', FTC = 'A', TYPE = '%');
SERIES RMORT@US.|#MYFREQ|  '30-YEAR MORTGAGE RATE, U.S.' SOURCE='FHL';
END;


ASSIGN AVAIL EXIST STKNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES STKNS@US.|#MYFREQ| (ORIGIN='http://finance.yahoo.com/q?s=%5EGSPC', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES STKNS@US.|#MYFREQ|  'EQUITY PRICE INDEX (S&P 500), U.S.' SOURCE='S&P';
END;


ASSIGN AVAIL EXIST UR@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES UR@CA.|#MYFREQ| (ORIGIN='http://www.bls.gov/lau/home.htm', UNITS='%', FTC = 'A', TYPE = '%');
SERIES UR@CA.|#MYFREQ|  'UNEMPLOYMENT RATE, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST URNS@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES URNS@CA.|#MYFREQ| (ORIGIN='http://www.bls.gov/lau/home.htm', UNITS='%', FTC = 'A', TYPE = '%');
SERIES URNS@CA.|#MYFREQ|  'UNEMPLOYMENT RATE, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST UR@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES UR@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cps/home.htm', UNITS='%', FTC = 'A', TYPE = '%');
SERIES UR@US.|#MYFREQ|  'UNEMPLOYMENT RATE, U.S.|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST URNS@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES URNS@US.|#MYFREQ| (ORIGIN='http://www.bls.gov/cps/home.htm', UNITS='%', FTC = 'A', TYPE = '%');
SERIES URNS@US.|#MYFREQ|  'UNEMPLOYMENT RATE, U.S.' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST Y@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES Y@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES Y@US.|#MYFREQ|  'PERSONAL INCOME, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YDPI@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YDPI@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES YDPI@US.|#MYFREQ|  'DISPOSABLE PERSONAL INCOME, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YCE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YCE@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES YCE@US.|#MYFREQ|  'PERSONAL CONSUMPTION EXPENDITURE, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YDPI_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YDPI_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$Bilc', FTC = 'A', TYPE = 'L');
SERIES YDPI_R@US.|#MYFREQ|  'REAL DISPOSABLE PERSONAL INCOME, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YCE_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YCE_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$Bilc', FTC = 'A', TYPE = 'L');
SERIES YCE_R@US.|#MYFREQ|  'REAL PERSONAL CONSUMPTION EXPENDITURE, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YPCDPI_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YPCDPI_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$c', FTC = 'A', TYPE = 'L');
SERIES YPCDPI_R@US.|#MYFREQ|  'REAL PER CAPITA DISPOSABLE INCOME, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST CAPUMN@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CAPUMN@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/CUMFN/', UNITS='%', FTC = 'A', TYPE = '%');
SERIES CAPUMN@US.|#MYFREQ|  'CAPACITY UTILIZATION, MANUFACTURING, U.S.' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST GDP@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP@US.|#MYFREQ|  'GROSS DOMESTIC PRODUCT, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GNP@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GNP@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GNP@US.|#MYFREQ|  'GROSS NATIONAL PRODUCT, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GDP_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$Bilc', FTC = 'A', TYPE = 'L');
SERIES GDP_R@US.|#MYFREQ|  'REAL GROSS DOMESTIC PRODUCT, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GNP_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GNP_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$Bilc', FTC = 'A', TYPE = 'L');
SERIES GNP_R@US.|#MYFREQ|  'REAL GNP, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YPC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YPC@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES YPC@US.|#MYFREQ|  'PER CAPITA PERSONAL INCOME, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YPCDPI@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YPCDPI@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES YPCDPI@US.|#MYFREQ|  'PER CAPITA DISPOSABLE INCOME, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YPCCE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YPCCE@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES YPCCE@US.|#MYFREQ|  'PER CAPITA CONSUMPTION EXPENDITURE, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GDPPC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDPPC@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES GDPPC@US.|#MYFREQ|  'PER CAPITA GDP, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GNPPC@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GNPPC@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES GNPPC@US.|#MYFREQ|  'PER CAPITA GNP, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST YPCCE_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES YPCCE_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$c', FTC = 'A', TYPE = 'L');
SERIES YPCCE_R@US.|#MYFREQ|  'REAL PER CAPITA CONSUMPTION EXPENDITURE, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GDPPC_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDPPC_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$c', FTC = 'A', TYPE = 'L');
SERIES GDPPC_R@US.|#MYFREQ|  'REAL PER CAPITA GDP, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GNPPC_R@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GNPPC_R@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='2005$c', FTC = 'A', TYPE = 'L');
SERIES GNPPC_R@US.|#MYFREQ|  'REAL PER CAPITA GNP, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST GDPDEF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDPDEF@US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='index', FTC = 'N', TYPE = 'L');
SERIES GDPDEF@US.|#MYFREQ|  'GDP DEFLATOR, U.S.|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST Y_R@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES Y_R@CA.|#MYFREQ| (ORIGIN='California income deflated by the California CPI', UNITS='82-84$Mil', FTC = 'A', TYPE = 'L');
SERIES Y_R@CA.|#MYFREQ|  'REAL PERSONAL INCOME, CALIFORNIA|#SEASNAME|' SOURCE='CALC';
END;


ASSIGN AVAIL EXIST Y@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES Y@CA.|#MYFREQ| (ORIGIN='http://www.bea.doc.gov/bea/regional/sqpi/', UNITS='$Mil', FTC = 'A', TYPE = 'L');
SERIES Y@CA.|#MYFREQ|  'PERSONAL INCOME, CALIFORNIA|#SEASNAME|' SOURCE='BEA';
END;


ASSIGN AVAIL EXIST CPI@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES CPI@CA.|#MYFREQ| (ORIGIN='http://www.dof.ca.gov/HTML/FS_DATA/LatestEconData/FS_Price.htm', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES CPI@CA.|#MYFREQ|  'CONSUMER PRICE INDEX (82-84=100), CALIFORNIA|#SEASNAME|' SOURCE='CADFIN';
END;


ASSIGN AVAIL EXIST INF@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES INF@CA.|#MYFREQ| (ORIGIN='year-to-year percent change in California CPI', UNITS='%', FTC = 'A', TYPE = '%');
SERIES INF@CA.|#MYFREQ|  'INFLATION RATE, CALIFORNIA' SOURCE='CALC';
END;


ASSIGN AVAIL EXIST EMPL@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMPL@CA.|#MYFREQ| (ORIGIN='http://www.bls.gov/sae/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMPL@CA.|#MYFREQ|  'EMPLOYMENT, CALIFORNIA|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST EMPLNS@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EMPLNS@CA.|#MYFREQ| (ORIGIN='http://www.bls.gov/sae/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES EMPLNS@CA.|#MYFREQ|  'EMPLOYMENT, CALIFORNIA' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST LF@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES LF@CA.|#MYFREQ| (ORIGIN='http://www.bls.gov/sae/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES LF@CA.|#MYFREQ|  'CIVILIAN LABOR FORCE, CALIFORNIA|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST LFNS@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES LFNS@CA.|#MYFREQ| (ORIGIN='http://www.bls.gov/sae/home.htm', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES LFNS@CA.|#MYFREQ|  'CIVILIAN LABOR FORCE, CALIFORNIA' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ENF@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ENF@CA.|#MYFREQ| (ORIGIN='http://data.bls.gov/cgi-bin/srgate', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ENF@CA.|#MYFREQ|  'TOTAL NON-FARM JOBS, CALIFORNIA|#SEASNAME|' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST ENFNS@CA;
IF ('#AVAIL' == '1');
DOCUMENT SERIES ENFNS@CA.|#MYFREQ| (ORIGIN='http://data.bls.gov/cgi-bin/srgate', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES ENFNS@CA.|#MYFREQ|  'TOTAL NON-FARM JOBS, CALIFORNIA' SOURCE='BLS';
END;


ASSIGN AVAIL EXIST INFGDPDEF@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES INFGDPDEF@US.|#MYFREQ| (ORIGIN='PCHYA(GDPDEF@US)', UNITS='%', FTC = 'A', TYPE = '%');
SERIES INFGDPDEF@US.|#MYFREQ|  'GDP DEFLATOR INFLATION RATE, U.S.|#SEASNAME|' SOURCE='CALC';
END;


ASSIGN AVAIL EXIST RAAA@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES RAAA@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/AAA/', UNITS='%', FTC = 'A', TYPE = '%');
SERIES RAAA@US.|#MYFREQ|  'Moody Seasoned Aaa Corporate Bond Yield, U.S.' SOURCE='SLFED';
END;

ASSIGN AVAIL EXIST STK@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES STK@US.|#MYFREQ| (ORIGIN='http://www.neatideas.com/data/index.htm', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES STK@US.|#MYFREQ|  'Equity Price Index (S&P 500), U.S.' SOURCE='S&P';
END;


ASSIGN AVAIL EXIST PCE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES PCE@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/PCEPI/', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES PCE@US.|#MYFREQ|  'PERSONAL CONSUMPTION EXPENDITURES CHAIN-TYPE PRICE INDEX, U.S.|#SEASNAME|' SOURCE='SLFED';
END;

ASSIGN AVAIL EXIST PCECORE@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES PCECORE@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/PCEPILFE', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES PCECORE@US.|#MYFREQ|  'PERSONAL CONSUMPTION EXPENDITURES CHAIN-TYPE PRICE INDEX (CORE), U.S.|#SEASNAME|' SOURCE='SLFED';
END;

ASSIGN AVAIL EXIST HOUST@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES HOUST@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/HOUST', UNITS='Thous', FTC = 'A', TYPE = 'L');
SERIES HOUST@US.|#MYFREQ|  'HOUSING STARTS, U.S.|#SEASNAME|' SOURCE='SLFED';
END;

ASSIGN AVAIL EXIST UMCSENT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES UMCSENT@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/UMCSENT/', UNITS='index', FTC = 'A', TYPE = 'L');
SERIES UMCSENT@US.|#MYFREQ|  'U OF MICHIGAN CONSUMER SENTIMENT INDEX, U.S.|#SEASNAME|' SOURCE='SLFED';
END;


ASSIGN AVAIL EXIST POIL@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES POIL@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/OILPRICE.', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES POIL@US.|#MYFREQ|  'SPOT OIL PRICE: WEST TEXAS INTERMEDIATE' SOURCE='SLFED';
END;

ASSIGN AVAIL EXIST BRENT@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES BRENT@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/MCOILBRENTEU.', UNITS='$', FTC = 'A', TYPE = 'L');
SERIES BRENT@US.|#MYFREQ|  'CRUDE OIL PRICES: BRENT - EUROPE' SOURCE='SLFED';
END;



ASSIGN AVAIL EXIST EXUSEU@US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES EXUSEU@US.|#MYFREQ| (ORIGIN='http://research.stlouisfed.org/fred2/series/EXUSEU', UNITS='Dollar/Euro', FTC = 'A', TYPE = 'L');
SERIES EXUSEU@US.|#MYFREQ|  'DOLLAR-EURO EXCHANGE RATE' SOURCE='SLFED';
END;

!---- components of GDP

FOR REALDOC = @,_R@;

IF ('#REALDOC'=='_R@'); 
 ASSIGN REALDOCNAME LITERAL ' IN CHAINED 2005 DOLLARS'; 
 ASSIGN UNIT        LITERAL '$Bil'; 
ELSE 
 ASSIGN REALDOCNAME LITERAL ''; 
 ASSIGN UNIT        LITERAL '$2005Bil'; 
END;



ASSIGN AVAIL EXIST GDP_C|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_C|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_C|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, CONSUMPTION, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_CD|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_CD|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_CD|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, DURABLE GOODS CONSUMPTION, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_CN|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_CN|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_CN|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, NONDURABLE CONSUMPTION, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_CS|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_CS|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_CS|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, SERVICES CONSUMPTION, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_I|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_I|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_I|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, INVESTMENT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_IFX|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_IFX|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_IFX|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, FIXED INVESTMENT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_INR|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_INR|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_INR|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, NONRESIDENTIAL INVESTMENT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_IRS|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_IRS|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_IRS|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, RESIDENTIAL INVESTMENT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_IIV|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_IIV|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_IIV|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, CHANGES IN INVENTORIES, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_NX|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_NX|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_NX|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, NET EXPORT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_EX|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_EX|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_EX|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, EXPORT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_IM|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_IM|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_IM|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, IMPORT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;

ASSIGN AVAIL EXIST GDP_G|#REALDOC|US;
IF ('#AVAIL' == '1');
DOCUMENT SERIES GDP_G|#REALDOC|US.|#MYFREQ| (ORIGIN='http://www.bea.gov/', UNITS='$Bil', FTC = 'A', TYPE = 'L');
SERIES GDP_G|#REALDOC|US.|#MYFREQ|  'GDP COMPONENTS, GOVERNMENT CONSUMPTION & INVESTMENT, U.S.|#SEASNAME|#REALDOCNAME|.' SOURCE='BEA';
END;



END; ! REALDOC






!*****************************

OPEN <PROTECT YES> #DBNK;
TELL "REPORT: END OF US_DOC.CMD";




